"""Write docs/DATA_QUALITY.md from data/data_quality_report.csv and the other cleaning outputs."""
from __future__ import annotations

import json
import sys
from pathlib import Path

import pandas as pd

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))
from src import config  # noqa: E402

CAT = {
    "A_split_bonus": "A. Splits, bonus issues, rights issues and dividends",
    "B_demerger": "B. Demergers and capital reductions",
    "C_symbol": "C. Symbol changes, listings and re-listings",
    "D_bad_print": "D. Bad prints and outliers",
    "E_calendar": "E. Calendar, gaps and alignment",
    "F_integrity": "F. Snapshot integrity",
}
FIXED_WORDS = ("replaced", "applied", "adjusted", "dropped", "filled", "set to missing", "rescaled", "treated", "used NSE", "added")


def md_table(df: pd.DataFrame) -> str:
    cols = list(df.columns)
    out = ["| " + " | ".join(cols) + " |", "|" + "---|" * len(cols)]
    for _, r in df.iterrows():
        out.append("| " + " | ".join(str(r[c]).replace("|", "/").replace("\n", " ") for c in cols) + " |")
    return "\n".join(out)


def main() -> None:
    D = config.DATA_DIR
    rep = pd.read_csv(D / "data_quality_report.csv")
    uni = pd.read_csv(D / "universe.csv")
    ca = pd.read_csv(D / "corporate_actions.csv")
    meta = json.loads((D / "metadata.json").read_text())
    spots = pd.read_csv(D / "spot_checks.csv")
    anchor = pd.read_csv(D / "nse_anchor.csv")
    excl = pd.read_csv(D / "excluded_returns.csv")
    sc = pd.read_csv(D / "symbol_changes.csv")

    rep["fixed"] = rep["action"].astype(str).str.contains("|".join(FIXED_WORDS), case=False)
    rep["excluded"] = rep["action"].astype(str).str.contains("excluded|fails the continuous", case=False)
    by_cat = rep.groupby("category").agg(detections=("issue", "size"), fixed=("fixed", "sum"),
                                         exclusions=("excluded", "sum")).reset_index()
    by_cat["category"] = by_cat["category"].map(CAT)

    L = []
    L.append("# Data quality report\n")
    L.append(f"Snapshot as of **{meta['as_of']}** · history from **{meta['history_start']}** · "
             f"{meta['sessions']:,} Nifty 50 sessions · prices SHA-256 `{meta['prices_sha256'][:16]}…`\n")
    L.append("Generated by `scripts/quality_doc.py` from `data/data_quality_report.csv` "
             f"({len(rep):,} rows; every detection and fix, with evidence and source).\n")
    L.append("## Summary\n")
    L.append(f"* **Stocks checked:** {meta['n_constituents']} Nifty 200 constituents (NSE list), plus the Nifty 50 and India VIX.")
    L.append(f"* **Core universe** (continuous history from {meta['history_start']}): **{meta['n_core']}** stocks.")
    L.append(f"* **Extended** (at least 3 years of clean history; usable for custom picks, earlier events greyed out): **{meta['n_extended']}**.")
    L.append(f"* **Excluded:** **{meta['n_excluded']}** (all listed under three years ago).")
    L.append(f"* **Spot checks against NSE official closes:** {int(spots['within_1pct'].sum())} of {len(spots)} within 1% "
             f"(max difference {spots['difference'].abs().max():.3%}).\n")
    L.append(md_table(by_cat) + "\n")

    L.append("## How the prices were rebuilt\n")
    L.append("1. **Yahoo raw prices.** Yahoo's `Close` (downloaded with `auto_adjust=False`) is already divided by every split Yahoo knows about. "
             "We undo that with Yahoo's own split history to get Yahoo's view of the exchange price.")
    L.append("2. **Anchored to NSE.** On the first trading day of every month we compare that price with NSE's official close in the bhavcopy. "
             f"Wherever the ratio steps to a new level, we bisect day by day to the exact date and rescale. **{anchor['ticker'].nunique()} stocks** had "
             f"**{len(anchor)}** such hidden level errors in Yahoo — splits recorded with the wrong ratio, bonuses never recorded, or demergers Yahoo "
             "adjusted silently (e.g. Reliance × 0.923 before 20 Jul 2023).")
    L.append("3. **Our own adjustments.** Every split, bonus, rights issue and demerger is re-applied from NSE's corporate-action records "
             "(`data/corporate_actions.csv`, one row per action with its source), confirmed by the price move on the ex-date.")
    L.append("4. **Dividends** come from NSE's records (₹ per share, or % of face value for older notices) and are reinvested on the ex-date "
             "(price before ex-date × (1 − dividend ÷ previous close)). Result: a total-return price series.")
    L.append("5. **Checks** for decimal errors, spike-and-revert bad ticks (verified against NSE before removal), stale prices, gaps and calendar alignment.\n")

    for code, title in CAT.items():
        sub = rep[rep["category"] == code]
        if sub.empty:
            continue
        L.append(f"## {title}\n")
        t = sub.groupby("issue").agg(count=("ticker", "size"), stocks=("ticker", "nunique"),
                                     typical_action=("action", lambda s: s.mode().iat[0][:110])).reset_index()
        L.append(md_table(t) + "\n")
        if code == "B_demerger":
            L.append(md_table(sub[["ticker", "date", "issue", "evidence", "source"]]) + "\n")
        if code == "C_symbol":
            L.append(md_table(sub[["ticker", "date", "issue", "evidence"]]) + "\n")

    L.append("## Corporate actions applied\n")
    applied = ca[ca["applied"] == True]  # noqa: E712
    L.append(f"{len(applied)} adjustments applied across {applied['ticker'].nunique()} stocks "
             f"({', '.join(f'{k}: {v}' for k, v in applied['type'].value_counts().items())}). Full list with sources: `data/corporate_actions.csv`.\n")
    L.append("Single-day returns dropped (demergers without a verifiable official ratio, treated as missing rather than a loss): "
             f"{len(excl)} — listed in `data/excluded_returns.csv`.\n")
    L.append("## Symbol changes\n")
    L.append(f"{len(sc)} symbol changes affect today's Nifty 200 names (`data/symbol_changes.csv`, from NSE's symbol-change list; "
             "one rename missing from that list — COLGATE → COLPAL — was established from NSE bhavcopies). Yahoo carries each stock's full "
             "history under its current symbol; NSE checks use the old symbol before the change date.\n")
    L.append("## Excluded stocks and shorter histories\n")
    L.append(md_table(uni[uni["status"] != "core"][["symbol", "industry", "status", "first_date", "reason"]]) + "\n")
    L.append("## Spot checks against NSE\n")
    L.append(md_table(spots) + "\n")
    L.append("## Benchmark caveat\n")
    L.append("Stock prices here include reinvested dividends, but the Nifty 50 (`^NSEI`) is a *price* index. Beta and every "
             "'versus Nifty 50' comparison therefore slightly favour the stocks (by roughly the index dividend yield, about 1–1.5% a year).\n")
    L.append("## Residual issues to keep in mind\n")
    L.append("* Six Nifty 50 sessions before 2012 are missing from Yahoo and NSE's archive has no index file for them; they are left out "
             "of the calendar, so the stock returns of those days merge into the next session.")
    L.append("* Older demergers (before NSE's 2023 special pre-open methodology) have their ex-date return dropped rather than adjusted.")
    L.append("* Rights issues use the theoretical ex-rights price; partly-paid issues and warrants are not adjusted.")
    (config.DOCS_DIR / "DATA_QUALITY.md").write_text("\n".join(L))
    print("wrote docs/DATA_QUALITY.md")


if __name__ == "__main__":
    main()
