"""Print every headline result and write docs/RESULTS_SUMMARY.md (numbers for the team to quote).

Reads results/default.json (run scripts/precompute.py first).
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

import numpy as np

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))
from src import config  # noqa: E402
from src import recommend as RC  # noqa: E402
from src import stats_tests as ST  # noqa: E402
from src.fmt import inr, inr_short, pct  # noqa: E402

AMT = config.AMOUNT_A


def tbl(rows, cols):
    out = ["| " + " | ".join(cols) + " |", "|" + "---|" * len(cols)]
    out += ["| " + " | ".join(str(x) for x in r) + " |" for r in rows]
    return "\n".join(out)


def main() -> None:
    res = json.loads((config.RESULTS_DIR / "default.json").read_text())
    uni = {r["symbol"]: r for r in json.loads((config.RESULTS_DIR / "universe.json").read_text())}
    P = res["portfolios"]
    ev = res["evidence"]
    off = res["official"]
    crisis = res["regimes"][f"{off['crisis']}|standard"]
    calm = res["regimes"][f"{off['calm']}|standard"]
    cur = res["current"]
    board = res["scoreboard"]["standard"]
    bA, bB = res["bootstrap"]["A"], res["bootstrap"]["B"]
    E = res["events"]
    L = []
    say = L.append

    say("# Results summary\n")
    say(f"Generated by `scripts/run_analysis.py` from the snapshot as of **{res['as_of']}**. Amount used for ₹ figures: "
        f"**{inr(AMT)}** in each portfolio (the app rescales every ₹ figure to the client's amount).\n")
    say(f"Official periods (auto picks from the regime finder): **crisis = {E[off['crisis']]['label']}**; "
        f"**calm = {E[off['calm']]['label']}**. Current window: {cur['start']} → {cur['end']}.\n")

    say("## 1. The two portfolios\n")
    for k in "AB":
        p = P[k]
        say(f"**Portfolio {k}** — objective `{p['objective']}`; expected return {pct(p['expected_return'])}, volatility "
            f"{pct(p['expected_vol'])}, Sharpe {p['sharpe']:.2f} (current window, risk-free {pct(config.RISK_FREE_RATE, 2)}).\n")
        rows = [(s, uni[s]["company"], uni[s]["industry"], uni[s]["cap_bucket"], f"{uni[s]['beta']:.2f}", pct(uni[s]["volatility"]),
                 uni[s]["label"], pct(p["weights"][s]), inr(p["weights"][s] * AMT)) for s in p["symbols"]]
        say(tbl(rows, ["Symbol", "Company", "Industry", "Cap", "Beta (3y)", "Vol (3y)", "Label", "Weight", "₹ on 15 lakh"]) + "\n")
        say("Industry weights: " + ", ".join(f"{i} {pct(w)}" for i, w in p["industry_weights"].items()) + "\n")

    say("## 2. The call — why A is high risk and B is low risk (trailing 3 years)\n")
    a, b = ev["A"], ev["B"]
    rows = [("Weighted beta", f"{a['weighted_beta']:.2f}", f"{b['weighted_beta']:.2f}"),
            ("Portfolio volatility √(wᵀΣw)", pct(a["portfolio_vol"]), pct(b["portfolio_vol"])),
            ("Maximum drawdown", pct(a["max_drawdown"]), pct(b["max_drawdown"])),
            ("Average pairwise correlation", f"{a['avg_pairwise_corr']:.2f}", f"{b['avg_pairwise_corr']:.2f}"),
            ("Large-cap share", pct(a["cap_mix"].get("Large cap", 0)), pct(b["cap_mix"].get("Large cap", 0)))]
    say(tbl(rows, ["Measure", "A", "B"]) + "\n")
    vr = ev["vol_ratio"]
    say(f"Volatility ratio σA/σB = **{vr['ratio']:.2f}**, block-bootstrap 95% CI **{vr['lo']:.2f} – {vr['hi']:.2f}** "
        f"({vr['resamples']} resamples, 5-day blocks) → the call is {'statistically backed (whole interval above 1)' if vr['significant'] else 'NOT statistically backed'}.\n")

    say("## 3. Optimum weights today — VaR before and after optimising (1-day, historical)\n")
    rows = []
    for k in "AB":
        vb = P[k]["var_before_after"]
        for c in ("0.95", "0.99"):
            rows.append((k, c, pct(vb["equal"]["Historical"][c]["var"], 2), pct(vb["optimised"]["Historical"][c]["var"], 2),
                         pct(vb["equal"]["Historical"][c]["es"], 2), pct(vb["optimised"]["Historical"][c]["es"], 2)))
    say(tbl(rows, ["Portfolio", "Confidence", "VaR equal-weight", "VaR optimised", "ES equal-weight", "ES optimised"]) + "\n")

    say("## 4. Test #1 — does the label hold? (official periods, standard 252-day windows)\n")
    rows = []
    for name, reg in (("Current", cur), ("Crisis", crisis), ("Calm", calm)):
        for k in "AB":
            r = reg[k]
            h = r["risk"]["Historical"]
            rows.append((name, k, pct(h["0.95"]["var"], 2), pct(h["0.99"]["var"], 2), pct(h["0.99"]["es"], 2), pct(h["0.975"]["es"], 2),
                         pct(r["volatility"]), f"{r['beta']:.2f}", pct(r["max_drawdown"]), pct(r["worst_day"], 1),
                         f"{r['avg_pairwise_corr']:.2f}", inr_short(h["0.99"]["es"] * AMT)))
    say(tbl(rows, ["Regime", "P", "VaR95", "VaR99", "ES99", "ES97.5", "Vol", "Beta", "Max DD", "Worst day", "Avg corr", "ES99 on ₹15L"]) + "\n")
    say("VaR/ES (99%, 1-day) by method in the official crisis:\n")
    rows = []
    for m in ("Historical", "Parametric normal", "Monte Carlo (Student-t)", "Cornish–Fisher"):
        rows.append((m, pct(crisis["A"]["risk"][m]["0.99"]["var"], 2), pct(crisis["A"]["risk"][m]["0.99"]["es"], 2),
                     pct(crisis["B"]["risk"][m]["0.99"]["var"], 2), pct(crisis["B"]["risk"][m]["0.99"]["es"], 2)))
    say(tbl(rows, ["Method", "A VaR99", "A ES99", "B VaR99", "B ES99"]) + "\n")
    lv = RC.label_verdict(crisis, calm, board)
    bv = RC.b_verdict(crisis, board)
    say(f"* High-risk label held: crisis **{lv['crisis']}**, calm **{lv['calm']}**, all events **{lv['events_held']}/{lv['events_total']}** → verdict **{lv['verdict']}**.")
    say(f"* B held up (ES and drawdown below the Nifty 50's) in the official crisis: **{bv['crisis']}**; across crises {bv['crises_held']}/{bv['crises_total']} → **{bv['verdict']}**.")
    for k in "AB":
        st = crisis[k]["stability"]
        say(f"* Label stability in the crisis: {st['same']} of {st['of']} of {k}'s stocks keep their label "
            f"({'High' if k == 'A' else 'Low'} risk) when the rule is re-run on crisis data.")
    for k in "AB":
        for nm, regw in (("calm", calm), ("current", cur)):
            bt = ST.breach_test(np.array(regw[k]["returns"]["port"]), np.array(crisis[k]["returns"]["port"]), 0.99)
            bt95 = ST.breach_test(np.array(regw[k]["returns"]["port"]), np.array(crisis[k]["returns"]["port"]), 0.95)
            say(f"* Breach test {k}, VaR calibrated on {nm}: 99% → expected about {bt['expected']:.1f}, got **{bt['breaches']}** "
                f"(Kupiec p = {bt['p_value']:.3g}); 95% → expected {bt95['expected']:.1f}, got **{bt95['breaches']}** (p = {bt95['p_value']:.3g}).")
    say(f"* Crisis replay on {inr(AMT)}: A lowest {inr(crisis['A']['replay']['low'] * AMT)} (fall {inr(crisis['A']['replay']['largest_fall'] * AMT)}), "
        f"B lowest {inr(crisis['B']['replay']['low'] * AMT)} (fall {inr(crisis['B']['replay']['largest_fall'] * AMT)}), Nifty 50 fall {pct(crisis['nifty']['largest_fall'])}.\n")

    say("## 5. Test #2 — would the optimiser still pick our weights?\n")
    rows = []
    for k, bs in (("A", bA), ("B", bB)):
        for nm, reg in (("Crisis", crisis), ("Calm", calm), ("Current", cur)):
            t = reg[k]["test2"]
            rows.append((k, nm, pct(t["target"]), t["case"], pct(t["ret"]), pct(t["vol"]), pct(t["turnover"]),
                         inr_short(t["turnover"] * AMT), pct(bs["turnover_p95"]), "yes" if t["turnover"] > bs["turnover_p95"] else "no",
                         pct(t["efficiency_gap"], 2)))
    say(tbl(rows, ["P", "Regime", "Target", "Case", "Regime-opt return", "Regime-opt vol", "Turnover", "₹ traded", "Noise p95", "Significant", "Efficiency gap"]) + "\n")
    for k in "AB":
        before = crisis[k]["risk"]["Historical"]["0.99"]
        after = crisis[k]["test2"]["var_after"]["Historical"]["0.99"]
        say(f"* {k} in the crisis — VaR99 before (today's weights) {pct(before['var'], 2)} → after (crisis-optimal) {pct(after['var'], 2)}; "
            f"ES99 {pct(before['es'], 2)} → {pct(after['es'], 2)}.")
    say("")

    say("## 6. All-events scoreboard (standard windows)\n")
    rows = [(r["event"], r["type"], f"{r['start']} → {r['end']}", pct(r["es99_A"], 2), pct(r["es99_B"], 2), pct(r["vol_A"]), pct(r["vol_B"]),
             pct(r["mdd_A"]), pct(r["mdd_B"]), inr_short(r["fall_A"] * AMT), inr_short(r["fall_B"] * AMT),
             "✓" if r["label_held"] else "✗", ("✓" if r["b_held_up"] else "✗") if r["type"] == "crisis" else "—") for r in board]
    say(tbl(rows, ["Event", "Type", "Window", "ES99 A", "ES99 B", "Vol A", "Vol B", "MDD A", "MDD B", "Worst ₹ fall A", "Worst ₹ fall B", "Label held", "B beat Nifty"]) + "\n")

    say("## 7. Verdict\n")
    rob = {k: RC.robustness(crisis[k]["test2"]["turnover"], calm[k]["test2"]["turnover"], res["bootstrap"][k]["turnover_p95"]) for k in "AB"}
    say(f"* Label: **{lv['verdict']}** for A; B held up: **{bv['verdict']}**.")
    say(f"* Weight robustness: A **{rob['A']['verdict']}**, B **{rob['B']['verdict']}**.")
    say(f"* Worst case on {inr(AMT)} (official crisis): A replay fall {inr(crisis['A']['replay']['largest_fall'] * AMT)}, ES99 {inr(crisis['A']['risk']['Historical']['0.99']['es'] * AMT)}/day; "
        f"B replay fall {inr(crisis['B']['replay']['largest_fall'] * AMT)}, ES99 {inr(crisis['B']['risk']['Historical']['0.99']['es'] * AMT)}/day.")
    trig = RC.review_trigger(np.diff(np.log(crisis["nifty"]["value"])).tolist())
    say(f"* Review trigger: revisit when the Nifty 50's 3-month volatility exceeds {pct(trig)}.\n")

    say("## 8. Regime finder — top candidates\n")
    rf = res["regime_finder"]
    for kind in ("crisis", "calm"):
        rows = [(c["start"], c["end"], pct(c["return"]), pct(c["volatility"]), pct(c["max_drawdown"]), pct(c["worst_day"]), pct(c["var99"], 2))
                for c in rf[f"{kind}_candidates"]]
        say(f"**{kind.title()} candidates**\n\n" + tbl(rows, ["Start", "End", "Return", "Vol", "Max DD", "Worst day", "VaR99"]) + "\n")

    text = "\n".join(L)
    (config.DOCS_DIR / "RESULTS_SUMMARY.md").write_text(text)
    print(text)


if __name__ == "__main__":
    main()
